name: 'Versioning'
inputs:
  bump:
    description: 'What to bump'
    required: false
    default: 'patch'
  source:
    description: 'Source to bump'
    required: true
outputs:
  version:
    description: "New Version Number"
    value: ${{ steps.set-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: dotnet tool install -g YadaYadaSoftware.Versioning
      shell: bash
    - id: set-version
      run: |
        VERSION=`dotnet version bump --what ${{ inputs.bump }} --source ${{inputs.source}}`
        echo "::set-output name=version::$VERSION"
      shell: bash