name: 'Versioning'
inputs:
  bump:
    description: 'What to bump'
    required: false
    default: 'patch'
  source:
    description: 'Source to bump'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: dotnet tool install -g YadaYadaSoftware.Versioning
      shell: bash
    - run: dotnet version bump --what ${{ inputs.bump }} --source ${{inputs.source}}
      shell: bash