name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      env:
        NUGET_AUTH_TOKEN: ${{github.token}}
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/yadayadasoftware/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Set Version
      run: echo "VERSION=2023.$(date +%j).${{ github.run_number }}" >> $GITHUB_ENV
    - name: Echo Version
      run: echo "VERSION=$VERSION"
    - name: Build
      run: dotnet build --no-restore -p:PackageVersion=$VERSION
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Push
      run: dotnet nuget push **/*.nupkg
